### ISSUE TITLE
No Licence

### ISSUE THREAD

**Issue by coline-carle** [diogogmt/humblebundle-downloader#7]
I have been forking your code and the changes done by @affinityv for my own use.

But as you two are legal holder of the copyright on your respective code, I don't even have the right to publish the changes I've done.

Could you add an open source license?

Or allow me to license my fork with an MIT Licence and credit you the way you think it's the most appropriate?

my fork: https://github.com/coline-carle/hb-downloader

**Comment by affinityv** [comment]
For the sake of licensing of my changes to this repository, I apply the MIT license.  Has your code got a license?  It doesn't seem to have any license files either. I can't talk for @diogogmt though and there is a very old pull request that hasn't been accepted, for whatever reason.

I've made more extensive changes to my own repository for various reasons, as you have done.

**Comment by diogogmt** [comment]
Added an MIT license to the repo.
